### ISSUE TITLE
Create the function to calculate GDD 

### ISSUE THREAD

**Issue by Ajay-Vijayakumar** [CMSC6950/GDD-Project--Team1#3]

**Comment by jmunroe** [comment]
You've assigned this task to both @GulamHaqqani and @David406.  Usually, tasks with multiple assignees make it difficult who is really responsible for the task.

**Comment by dw-wang** [comment]
I'm also gonna work on this part, otherwise I can't start secondary tasks.

**Comment by dw-wang** [comment]
I finished this code, please review and checked it out!

**Comment by Ajay-Vijayakumar** [comment]
the script works fine in calculating accumulated GDD. Can you please check the naming of the output file. Because when the "prefix" variable is empty, the output file name comes out as "-CumGDD.csv" which couldn't be opened in linux as the "-" is treated as some kind of option for a command.

**Comment by dw-wang** [comment]
Ok, I'll fix this
